### ISSUE TITLE
Pip install with error: metadata-generation-failed

### ISSUE THREAD

**Issue by pingzhili** [sheffieldnlp/fever-scorer#4]
I met some problem when I install fever-scorer(as well as fever-allennlp-reader) with pip
`pip install fever-scorer`

and I got an error when Preparing metadata (setup.py)

```
× python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [31 lines of output]
      running egg_info
      creating /private/var/folders/qt/t2jj1p_93v101wjd3zc55k_00000gn/T/pip-pip-egg-info-1ln59qi9/fever_scorer.egg-info
      writing /private/var/folders/qt/t2jj1p_93v101wjd3zc55k_00000gn/T/pip-pip-egg-info-1ln59qi9/fever_scorer.egg-info/PKG-INFO
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/qt/t2jj1p_93v101wjd3zc55k_00000gn/T/pip-install-c00ucld3/fever-scorer_0699642a161c4d2eb2f037d0b8f94bbc/setup.py", line 13, in <module>
          setup(
        File "/Users/lipingzhi/opt/anaconda3/envs/allennlp/lib/python3.8/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/Users/lipingzhi/opt/anaconda3/envs/allennlp/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/Users/lipingzhi/opt/anaconda3/envs/allennlp/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/Users/lipingzhi/opt/anaconda3/envs/allennlp/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/Users/lipingzhi/opt/anaconda3/envs/allennlp/lib/python3.8/site-packages/setuptools/dist.py", line 1208, in run_command
          super().run_command(command)
        File "/Users/lipingzhi/opt/anaconda3/envs/allennlp/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/Users/lipingzhi/opt/anaconda3/envs/allennlp/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 301, in run
          writer(self, ep.name, os.path.join(self.egg_info, ep.name))
        File "/Users/lipingzhi/opt/anaconda3/envs/allennlp/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 675, in write_pkg_info
          metadata.write_pkg_info(cmd.egg_info)
        File "/Users/lipingzhi/opt/anaconda3/envs/allennlp/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 1137, in write_pkg_info
          self.write_pkg_file(pkg_info)
        File "/Users/lipingzhi/opt/anaconda3/envs/allennlp/lib/python3.8/site-packages/setuptools/dist.py", line 196, in write_pkg_file
          write_field('License', rfc822_escape(license))
        File "/Users/lipingzhi/opt/anaconda3/envs/allennlp/lib/python3.8/site-packages/setuptools/_distutils/util.py", line 511, in rfc822_escape
          lines = header.split('\n')
      AttributeError: '_Printer' object has no attribute 'split'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by pingzhili** [comment]
problem solved by downgrading _setuptools_ package to 56.1.0 following [this](https://github.com/pypa/setuptools/issues/2741#issuecomment-885845791)
